holograms-visible: true
messages:
  prefix: "&aServer >>"
  reloaded: "%prefix% Reloaded successfully"
  command-usage: "%prefix% /lootchest <create | delete | get | edit | edititem | list | reload>"
  command-create-format: "%prefix% /lootchest create <id> <mininum items> <maximum items> [Rest of the args for display name]"
  command-delete-format: "%prefix% /lootchest delete <id>"
  command-get-format: "%prefix% /lootchest get <id> [amount]"
  command-give: "%prefix% /lootchest give <id> <player> [amount]"
  command-edit-format: "%prefix% /lootchest edit <id>"
  command-list-format: "%prefix% /lootchest list"
  command-edit-item: "%prefix% /lootchest edititem <id> <material> <min> <max>"
  command-fix: "%prefix% /lootchest fix <x> <y> <z> <x> <y> <z>"
  no-permission: "%prefix% You do not have permission to do this!"
  must-be-player: "%prefix% You must be a player to execute this command!"
  loot-chest-saved: "%prefix% %lootchest% saved"
  min-items-set: "%prefix% %lootchest%'s minimum items was set to %amount%"
  max-items-set: "%prefix% %lootchest%'s maximum items was set to %amount%"
  item-chances-set: "%prefix% %material% max set to %max% and min set to %min%"
  loot-chest-deleted: "%prefix% %lootchest% deleted"
  no-loot-chest-found: "%prefix% %lootchest% does not exist"
  hologram-display-not-looted: "%prefix% %lootchest%"
  hologram-display-looted: "%prefix% %lootchest% looted"
  player-not-online: "%prefix% %player% is not online!"
  fix-task-complete: "%prefix% Loot chests have been fixed"
  fixed-loot-chest-at: "%prefix% Fixed loot chests at %x%, %y%, %z%"
  checked-chunk: "%prefix% Checked chunk %x%, %z% for loot chests"
  starting-fix: "%prefix% Starting fix"
